### ISSUE TITLE
Fix openpack bug

### ISSUE THREAD

**Issue by lxgr-linux** [DecentralCardGame/Cardchain#182]
```
Cardchaind tx cardchain open-booster-pack 0 --from jannik
auth_info:
  fee:
    amount: []
    gas_limit: "200000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /DecentralCardGame.cardchain.cardchain.MsgOpenBoosterPack
    boosterPackId: "0"
    creator: cc14km80077s0hch3sh38wh2hfk7kxfau4456r3ej
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 111222
codespace: undefined
data: ""
events:
- attributes:
  - index: true
    key: ZmVl
    value: ""
  - index: true
    key: ZmVlX3BheWVy
    value: Y2MxNGttODAwNzdzMGhjaDNzaDM4d2gyaGZrN2t4ZmF1NDQ1NnIzZWo=
  type: tx
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: Y2MxNGttODAwNzdzMGhjaDNzaDM4d2gyaGZrN2t4ZmF1NDQ1NnIzZWovNjk5Mw==
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: YUNGSVBVYWVQTGM4ampwNWJWUlEzeExLOWRKOFo3Zi9LQklmVzk3KzhtNXoxTTNxakY2OWxRb1doSmUvcGJVNUZxcWhFYUJqTzVQQ2JObmdzRW9iS3c9PQ==
  type: tx
gas_used: "47484"
gas_wanted: "200000"
height: "87812"
info: ""
logs: []
raw_log: "recovered: invalid argument to Intn\nstack:\ngoroutine 32 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24
  +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func1({0x1e842c0,
  0x3032c10})\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/recovery.go:71
  +0x25\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func2({0x1e842c0?,
  0x3032c10?})\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/recovery.go:39
  +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1e842c0, 0x3032c10},
  0x20?)\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/recovery.go:28
  +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1e842c0, 0x3032c10},
  0x2000?)\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/recovery.go:33
  +0x53\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/baseapp.go:642
  +0xfe\npanic({0x1e842c0?, 0x3032c10?})\n\t/usr/local/go/src/runtime/panic.go:914
  +0x21f\nmath/rand.(*Rand).Intn(0xc03cdbfb00?, 0x0?)\n\t/usr/local/go/src/math/rand/rand.go:180
  +0x4c\nmath/rand.Intn(0x306bbd0?)\n\t/usr/local/go/src/math/rand/rand.go:453 +0x25\ngithub.com/DecentralCardGame/Cardchain/x/cardchain/keeper.msgServer.OpenBoosterPack({{{0x306bbd0,
  0xc0006cd1b0}, {0x303f450, 0xc001978540}, {0x303f450, 0xc0019785d0}, {{0x306bbd0,
  0xc0006cd1b0}, 0xc000611f08, {0x303f450, ...}, ...}, ...}}, ...)\n\t/root/cardchain/x/cardchain/keeper/msg_server_open_booster_pack.go:47
  +0x910\ngithub.com/DecentralCardGame/Cardchain/x/cardchain/types._Msg_OpenBoosterPack_Handler.func1({0x305b678,
  0xc031eae540}, {0x2203d60?, 0xc00f6394b8})\n\t/root/cardchain/x/cardchain/types/tx.pb.go:5286
  +0x75\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x305b090,
  0xc0368e2000}, {0xc039511b78?, 0x40fea5?}, 0x2a0?, 0xc00f639770)\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/msg_service_router.go:118
  +0x93\ngithub.com/DecentralCardGame/Cardchain/x/cardchain/types._Msg_OpenBoosterPack_Handler({0x227ca00?,
  0xc00018fc00}, {0x305b090, 0xc0368e2000}, 0x2bb03a8, 0xc04107c300)\n\t/root/cardchain/x/cardchain/types/tx.pb.go:5288
  +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x305af78,
  0x4394f00}, {0x306c290, 0xc00f601ec0}, {{0xb, 0x0}, {0xc038998290, 0xc}, 0x15704,
  {0x117c1ac, ...}, ...}, ...}, ...)\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/msg_service_router.go:145
  +0x3a3\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x305af78,
  0x4394f00}, {0x306c290, 0xc00f601ec0}, {{0xb, 0x0}, {0xc038998290, 0xc}, 0x15704,
  ...}, ...}, ...)\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/baseapp.go:788
  +0x285\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000f59a40, 0x3,
  {0xc02dabd560, 0x109, 0x109})\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/baseapp.go:728
  +0xd05\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0xc000f59a40,
  {{0xc02dabd560?, 0x18?, 0x0?}})\n\t/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/abci.go:283
  +0x178\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc0011cc8a0,
  {{0xc02dabd560?, 0x0?, 0xc0011cc8a0?}})\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/abci/client/local_client.go:93
  +0xf9\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc05c7f61c0?,
  {{0xc02dabd560?, 0x20?, 0xb?}})\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/proxy/app_conn.go:85
  +0x22\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x305afe8?, 0xc00681cf00},
  {0x3064bb0, 0xc0011cedb0}, 0xc00716af00, {0x306c800, 0xc001d9eb70}, 0x15703?)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/state/execution.go:320
  +0x6c9\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb,
  0x0}, {0xc013d56ba0, 0x7}}, {0xc013d56bb0, 0xc}, 0x1, 0x15703, {{0xc032f54da0, ...},
  ...}, ...}, ...)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/state/execution.go:140
  +0x16b\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000485c00,
  0x15704)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:1661
  +0xadd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000485c00,
  0x15704)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:1570
  +0x2f6\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:1505
  +0x9c\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000485c00,
  0x15704, 0x0)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:1543
  +0xc5f\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000485c00,
  0xc02a1b3360, {0x0, 0x0})\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:2164
  +0x17a5\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000485c00,
  0xc02a1b3360, {0x0?, 0x480ed0?})\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:1962
  +0x26\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000485c00,
  {{0x3039980, 0xc000610e20}, {0x0, 0x0}})\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:861
  +0x3ce\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000485c00,
  0x0)\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:788
  +0x4bc\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart in
  goroutine 9\n\t/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.29/consensus/state.go:379
  +0x10c\n: panic"
timestamp: ""
tx: null
txhash: 824A926BB4B5F84683FA0AF7DB64EB8A0ABA0B261C8271C550C50DB48960A985

```

**Comment by lxgr-linux** [comment]
This is due to the "yannik" test account having old invalid boosters.
